import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { toast } from 'sonner';
import { Calendar, Clock, Send, List, Facebook, Twitter, Linkedin, Instagram, Upload, Sparkles, FileText, Repeat } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { supabase } from '@/integrations/supabase/client';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { addDays, set } from 'date-fns';
import * as pdfjsLib from 'pdfjs-dist';

const formSchema = z.object({
  platforms: z.array(z.string()).nonempty({
    message: 'Please select at least one platform.',
  }),
  time: z.string().min(1, 'Please select a time.'),
  contentType: z.enum(['manual', 'pdf', 'ai']).default('manual'),
  content: z.string().optional(),
  pdfFile: z.any().optional(),
  aiPrompt: z.string().optional(),
  scheduleType: z.enum(['specificDate', 'recurring']).default('specificDate'),
  specificDate: z.string().optional(),
  recurringDays: z.array(z.string()).optional(),
}).superRefine((data, ctx) => {
  if (data.contentType === 'manual' && (!data.content || data.content.trim().length === 0)) {
    ctx.addIssue({ code: 'custom', path: ['content'], message: 'Content cannot be empty.' });
  }
  if (data.contentType === 'pdf' && (!data.pdfFile || data.pdfFile.length === 0)) {
    ctx.addIssue({ code: 'custom', path: ['pdfFile'], message: 'Please upload a PDF file.' });
  }
  if (data.contentType === 'ai' && (!data.aiPrompt || data.aiPrompt.trim().length === 0)) {
    ctx.addIssue({ code: 'custom', path: ['aiPrompt'], message: 'AI prompt cannot be empty.' });
  }
  if (data.scheduleType === 'specificDate' && !data.specificDate) {
    ctx.addIssue({ code: 'custom', path: ['specificDate'], message: 'Please select a date.' });
  }
  if (data.scheduleType === 'recurring' && (!data.recurringDays || data.recurringDays.length === 0)) {
    ctx.addIssue({ code: 'custom', path: ['recurringDays'], message: 'Please select at least one day.' });
  }
});

const platformOptions = [
    { id: 'Facebook', label: 'Facebook', icon: Facebook },
    { id: 'Twitter', label: 'Twitter', icon: Twitter },
    { id: 'LinkedIn', label: 'LinkedIn', icon: Linkedin },
    { id: 'Instagram', label: 'Instagram', icon: Instagram },
];

const dayOfWeekOptions = [
    { id: 'monday', label: 'Monday' },
    { id: 'tuesday', label: 'Tuesday' },
    { id: 'wednesday', label: 'Wednesday' },
    { id: 'thursday', label: 'Thursday' },
    { id: 'friday', label: 'Friday' },
    { id: 'saturday', label: 'Saturday' },
    { id: 'sunday', label: 'Sunday' },
];

const dayMapping: { [key: string]: number } = {
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
};

interface Post {
  id: number;
  platform: string;
  content: string;
  date: string;
  time: string;
  status: string;
  scheduled_at: Date;
  imageUrl?: string;
  attachmentName?: string;
}

pdfjsLib.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@4.4.178/build/pdf.worker.mjs`;

const getTextFromPdf = async (file: File): Promise<string> => {
    const uri = URL.createObjectURL(file);
    const pdf = await pdfjsLib.getDocument(uri).promise;
    let content = '';
    for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        content += textContent.items.map((item: any) => item.str).join(' ');
    }
    URL.revokeObjectURL(uri);
    return content;
};

const AutopostingSocialMediaAgent = ({ agent }) => {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadingMessage, setLoadingMessage] = useState('Scheduling...');

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      platforms: [],
      content: '',
      time: '',
      contentType: 'manual',
      aiPrompt: '',
      scheduleType: 'specificDate',
      specificDate: '',
      recurringDays: [],
    },
  });

  // ---- PATCH: Fix type issue for scheduled_posts (SUPABASE types do not know about this table yet)
  // @ts-expect-error: scheduled_posts is missing from autogenerated types
  const scheduleTwitterPost = async ({
    content,
    scheduled_at,
  }: { content: string; scheduled_at: Date }) => {
    const { error } = await supabase.from('scheduled_posts').insert({
      platform: "twitter",
      content,
      scheduled_at: scheduled_at.toISOString(),
    });
    if (error) throw new Error(error.message);
    return true;
  };

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    setLoading(true);
    let postContent: string | undefined = values.content;
    let imageUrl: string | undefined = undefined;
    let attachmentName: string | undefined = undefined;

    try {
      if (values.contentType === 'ai') {
        setLoadingMessage('Generating AI content...');
        const { data, error } = await supabase.functions.invoke('generate-text-content', {
          body: { prompt: values.aiPrompt },
        });
        if (error) {
          throw new Error(error.message);
        }
        postContent = data.generatedText;
      } else if (values.contentType === 'pdf') {
        setLoadingMessage('Processing PDF...');
        const file = values.pdfFile[0];
        attachmentName = file.name;
        postContent = await getTextFromPdf(file);
      }

      setLoadingMessage('Scheduling...');
      const newPosts: Post[] = [];
      const [hours, minutes] = values.time.split(':').map(Number);

      if (values.scheduleType === "specificDate" && values.specificDate) {
        const scheduled_at = new Date(`${values.specificDate}T${values.time}`);
        for (const platform of values.platforms) {
          if (platform.toLowerCase() === "twitter") {
            try {
              await scheduleTwitterPost({ content: postContent || "", scheduled_at });
              toast.success("Twitter post scheduled!");
            } catch (twitterErr: any) {
              toast.error("Failed to schedule Twitter post: " + twitterErr.message);
            }
          }
          newPosts.push({
            id: Date.now() + Math.random(),
            platform,
            content: postContent || "",
            date: values.specificDate!,
            time: values.time,
            status: "Scheduled",
            scheduled_at,
            imageUrl,
            attachmentName,
          });
        }
      } else if (values.scheduleType === "recurring" && values.recurringDays) {
        values.recurringDays.forEach(dayName => {
          const dayIndex = dayMapping[dayName.toLowerCase()];
          const now = new Date();
          const targetDateAtTime = set(now, { hours, minutes, seconds: 0, milliseconds: 0 });
          const currentDayIndex = now.getDay();
          let daysToAdd = dayIndex - currentDayIndex;
          if (daysToAdd < 0 || (daysToAdd === 0 && targetDateAtTime < now)) {
            daysToAdd += 7;
          }
          const scheduled_at = addDays(now, daysToAdd);
          const finalDate = set(scheduled_at, { hours, minutes, seconds: 0, milliseconds: 0 });

          values.platforms.forEach(platform => {
            if (platform.toLowerCase() === "twitter") {
              scheduleTwitterPost({ content: postContent || "", scheduled_at: finalDate })
                .then(() => toast.success("Twitter post scheduled!"))
                .catch((err) => toast.error("Failed to schedule Twitter post: " + err.message));
            }
            newPosts.push({
              id: Date.now() + Math.random(),
              platform,
              content: postContent || "",
              date: finalDate.toISOString().split("T")[0],
              time: values.time,
              status: "Scheduled",
              scheduled_at: finalDate,
              imageUrl,
              attachmentName,
            });
          });
        });
      }

      setTimeout(() => {
        setPosts((prevPosts) => [...prevPosts, ...newPosts].sort((a, b) => a.scheduled_at.getTime() - b.scheduled_at.getTime()));
        toast.success(`Posts scheduled successfully!`);
        form.reset();
        setLoading(false);
      }, 500);

    } catch (error: any) {
      console.error('Error submitting post:', error);
      toast.error(`Failed to schedule post: ${error.message}`);
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <Tabs defaultValue="schedule" className="w-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="schedule">
            <Send className="mr-2 h-4 w-4" />
            Schedule Post
          </TabsTrigger>
          <TabsTrigger value="posts">
            <List className="mr-2 h-4 w-4" />
            Scheduled Posts ({posts.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="schedule">
          <Card>
            <CardHeader>
              <CardTitle>Create a new social media post</CardTitle>
            </CardHeader>
            <CardContent>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                  <FormField
                    control={form.control}
                    name="platforms"
                    render={() => (
                      <FormItem>
                        <div className="mb-4">
                            <FormLabel>Platforms</FormLabel>
                            <FormDescription>
                                Select the platforms you want to post to.
                            </FormDescription>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {platformOptions.map((item) => {
                                const Icon = item.icon;
                                return (
                                    <FormField
                                        key={item.id}
                                        control={form.control}
                                        name="platforms"
                                        render={({ field }) => {
                                            return (
                                                <FormItem
                                                    key={item.id}
                                                    className="flex flex-row items-center space-x-3 space-y-0 rounded-md border p-3 transition-colors hover:bg-accent hover:text-accent-foreground has-[:checked]:bg-accent"
                                                >
                                                    <FormControl>
                                                        <Checkbox
                                                            checked={field.value?.includes(item.id)}
                                                            onCheckedChange={(checked) => {
                                                                return checked
                                                                ? field.onChange([...(field.value || []), item.id])
                                                                : field.onChange(
                                                                    field.value?.filter(
                                                                        (value) => value !== item.id
                                                                    )
                                                                    );
                                                            }}
                                                        />
                                                    </FormControl>
                                                    <Icon className="h-5 w-5 text-muted-foreground" />
                                                    <FormLabel className="font-normal cursor-pointer flex-1 w-full">
                                                        {item.label}
                                                    </FormLabel>
                                                </FormItem>
                                            );
                                        }}
                                    />
                                )
                            })}
                        </div>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="contentType"
                    render={({ field }) => (
                      <FormItem>
                         <FormLabel>Content</FormLabel>
                         <Tabs defaultValue={field.value} onValueChange={field.onChange} className="w-full">
                            <TabsList className="grid w-full grid-cols-3">
                                <TabsTrigger value="manual"><FileText className="mr-2 h-4 w-4" />Manual</TabsTrigger>
                                <TabsTrigger value="pdf"><Upload className="mr-2 h-4 w-4" />From PDF</TabsTrigger>
                                <TabsTrigger value="ai"><Sparkles className="mr-2 h-4 w-4" />Generate with AI</TabsTrigger>
                            </TabsList>
                            <TabsContent value="manual" className="pt-4">
                                <FormField
                                    control={form.control}
                                    name="content"
                                    render={({ field }) => (
                                    <FormItem>
                                        <FormControl>
                                        <Textarea placeholder="What's on your mind?" {...field} rows={5} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                    )}
                                />
                            </TabsContent>
                            <TabsContent value="pdf" className="pt-4">
                                <FormField
                                    control={form.control}
                                    name="pdfFile"
                                    render={({ field: { onChange, ...fieldProps }}) => (
                                        <FormItem>
                                            <FormLabel>Upload PDF</FormLabel>
                                            <FormControl>
                                                <Input type="file" accept=".pdf" {...fieldProps} onChange={(e) => onChange(e.target.files)} />
                                            </FormControl>
                                            <FormDescription>Upload a PDF to extract content. Full processing coming soon.</FormDescription>
                                            <FormMessage />
                                        </FormItem>
                                    )}
                                />
                            </TabsContent>
                            <TabsContent value="ai" className="pt-4">
                                <FormField
                                    control={form.control}
                                    name="aiPrompt"
                                    render={({ field }) => (
                                    <FormItem>
                                        <FormControl>
                                            <Textarea placeholder="e.g., Write a post about the benefits of remote work" {...field} rows={5} />
                                        </FormControl>
                                        <FormDescription>Describe the content you want the AI to generate for your post.</FormDescription>
                                        <FormMessage />
                                    </FormItem>
                                    )}
                                />
                            </TabsContent>
                         </Tabs>
                      </FormItem>
                    )}
                  />
                  <div className="space-y-4 rounded-md border p-4">
                    <FormLabel>Scheduling</FormLabel>
                    <FormField
                      control={form.control}
                      name="scheduleType"
                      render={({ field }) => (
                        <FormItem>
                          <FormControl>
                            <RadioGroup
                              onValueChange={field.onChange}
                              defaultValue={field.value}
                              className="grid grid-cols-1 md:grid-cols-2 gap-4"
                            >
                              <FormItem className="flex flex-row items-center space-x-3 space-y-0 rounded-md border p-3 transition-colors hover:bg-accent hover:text-accent-foreground has-[:checked]:bg-accent">
                                <FormControl>
                                  <RadioGroupItem value="specificDate" />
                                </FormControl>
                                <Calendar className="h-5 w-5 text-muted-foreground" />
                                <FormLabel className="font-normal cursor-pointer flex-1 w-full">
                                  Specific Date
                                </FormLabel>
                              </FormItem>
                              <FormItem className="flex flex-row items-center space-x-3 space-y-0 rounded-md border p-3 transition-colors hover:bg-accent hover:text-accent-foreground has-[:checked]:bg-accent">
                                <FormControl>
                                  <RadioGroupItem value="recurring" />
                                </FormControl>
                                <Repeat className="h-5 w-5 text-muted-foreground" />
                                <FormLabel className="font-normal cursor-pointer flex-1 w-full">
                                  Recurring
                                </FormLabel>
                              </FormItem>
                            </RadioGroup>
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    
                    {form.watch('scheduleType') === 'specificDate' && (
                       <FormField
                          control={form.control}
                          name="specificDate"
                          render={({ field }) => (
                            <FormItem>
                              <FormLabel>Date</FormLabel>
                              <FormControl>
                                <Input type="date" {...field} />
                              </FormControl>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                    )}

                    {form.watch('scheduleType') === 'recurring' && (
                        <FormField
                            control={form.control}
                            name="recurringDays"
                            render={() => (
                            <FormItem>
                                <div className="mb-4">
                                    <FormLabel>Days of the week</FormLabel>
                                    <FormDescription>
                                        Select the days you want to post on.
                                    </FormDescription>
                                </div>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                    {dayOfWeekOptions.map((item) => (
                                        <FormField
                                            key={item.id}
                                            control={form.control}
                                            name="recurringDays"
                                            render={({ field }) => {
                                                return (
                                                    <FormItem
                                                        key={item.id}
                                                        className="flex flex-row items-center space-x-3 space-y-0 rounded-md border p-3 transition-colors hover:bg-accent hover:text-accent-foreground has-[:checked]:bg-accent"
                                                    >
                                                        <FormControl>
                                                            <Checkbox
                                                                checked={field.value?.includes(item.id)}
                                                                onCheckedChange={(checked) => {
                                                                    return checked
                                                                    ? field.onChange([...(field.value || []), item.id])
                                                                    : field.onChange(
                                                                        field.value?.filter(
                                                                            (value) => value !== item.id
                                                                        )
                                                                        );
                                                                }}
                                                            />
                                                        </FormControl>
                                                        <FormLabel className="font-normal cursor-pointer flex-1 w-full">
                                                            {item.label}
                                                        </FormLabel>
                                                    </FormItem>
                                                );
                                            }}
                                        />
                                    ))}
                                </div>
                                <FormMessage />
                            </FormItem>
                            )}
                        />
                    )}

                    <FormField
                      control={form.control}
                      name="time"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Time</FormLabel>
                          <FormControl>
                            <Input type="time" {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                  <Button type="submit" disabled={loading} className="w-full">
                    {loading ? loadingMessage : 'Schedule Post'}
                  </Button>
                </form>
              </Form>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="posts">
          <Card>
            <CardHeader>
              <CardTitle>Your Scheduled Posts</CardTitle>
            </CardHeader>
            <CardContent>
              {posts.length > 0 ? (
                <div className="overflow-x-auto">
                  <table className="w-full border-collapse border border-border">
                    <thead>
                      <tr className="bg-muted">
                        <th className="border border-border p-2 text-left">Platform</th>
                        <th className="border border-border p-2 text-left">Content</th>
                        <th className="border border-border p-2 text-left">Scheduled For</th>
                        <th className="border border-border p-2 text-left">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {posts.sort((a, b) => a.scheduled_at.getTime() - b.scheduled_at.getTime()).map((post) => (
                        <tr key={post.id}>
                          <td className="border border-border p-2 capitalize">{post.platform}</td>
                          <td className="border border-border p-2 max-w-xs">
                            <div className="flex flex-col gap-2">
                                {post.imageUrl && <img src={post.imageUrl} alt="Generated content" className="w-24 h-24 object-cover rounded-md" />}
                                {post.attachmentName && (
                                    <div className="flex items-center gap-2 text-sm text-muted-foreground p-2 bg-muted rounded-md">
                                        <FileText className="h-4 w-4" />
                                        <span className="truncate">{post.attachmentName}</span>
                                    </div>
                                )}
                                <p className="truncate">{post.content}</p>
                            </div>
                          </td>
                          <td className="border border-border p-2 whitespace-nowrap">
                            {post.scheduled_at.toLocaleString()}
                          </td>
                          <td className="border border-border p-2">
                            <span className="px-2 py-1 text-xs font-medium rounded-full bg-blue-100 text-blue-800">
                              {post.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <p className="text-muted-foreground text-center py-8">
                  You have no posts scheduled yet.
                </p>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default AutopostingSocialMediaAgent;
