// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaojozbqboktlhtyvyrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhb2pvemJxYm9rdGxodHl2eXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjE0MDAsImV4cCI6MjA2MzU5NzQwMH0.N-IkS2bmj34mTm03rjwKfqqGOK4iVB3319DTYHzbD8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);